server:
  port: 8001

spring:
  application:
    name: cloud-consul-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liz_admin_database?useSSL=false&useAffectedRows=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: liz-admin
    password: a5206987454

  ###Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: localhost
      prot: 8500
      discovery:
        service-name: ${spring.application.name}

  # mybatis-plus \u914D\u7F6E
  mybatis-plus:
    # mybatis-config.xml\u6587\u4EF6\u8DEF\u5F84\u914D\u7F6E
    #  config-location: classpath:mybatis-config.xml
    mapper-locations:
      - mapper/*.xml
    type-aliases-package: com.lwu.entity.*
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl